-- MySQL Script generated by MySQL Workbench
-- Tue Sep 22 13:53:40 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_tiendita-saludable
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_tiendita-saludable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_tiendita-saludable` DEFAULT CHARACTER SET utf8 ;
USE `db_tiendita-saludable` ;

-- -----------------------------------------------------
-- Table `db_tiendita-saludable`.`ts_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tiendita-saludable`.`ts_categoria` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripción` VARCHAR(255) NULL,
  `activo` TINYINT NULL DEFAULT 1,
  `creado_en` DATE NULL DEFAULT on update CURRENT_TIMESTAMP,
  `mofificado_en` DATE NULL DEFAULT on update CURRENT_TIMESTAMP,
  `borrado_en` DATE NULL DEFAULT on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_tiendita-saludable`.`ts_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tiendita-saludable`.`ts_producto` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `ts_categoria_id` INT NOT NULL,
  `stock_actual` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ts_producto_ts_categoria1_idx` (`ts_categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_ts_producto_ts_categoria1`
    FOREIGN KEY (`ts_categoria_id`)
    REFERENCES `db_tiendita-saludable`.`ts_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tiendita-saludable`.`ts_tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tiendita-saludable`.`ts_tipo_usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(40) NULL,
  `descripcion` VARCHAR(45) NULL,
  `creado_en` DATETIME NULL DEFAULT on update CURRENT_TIMESTAMP,
  `borrado_en` DATETIME NULL DEFAULT on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_tiendita-saludable`.`ts_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tiendita-saludable`.`ts_usuario` (
  `id` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `nick_name` VARCHAR(25) NULL DEFAULT CURRENT_TIMESTAMP,
  `ts_tipo_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ts_usuario_ts_tipo_usuario1_idx` (`ts_tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_ts_usuario_ts_tipo_usuario1`
    FOREIGN KEY (`ts_tipo_usuario_id`)
    REFERENCES `db_tiendita-saludable`.`ts_tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_tiendita-saludable`.`ts_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tiendita-saludable`.`ts_cliente` (
  `id` INT NOT NULL,
  `nombres` VARCHAR(80) NULL,
  `apellidos` VARCHAR(80) NULL,
  `nro_whatsapp` VARCHAR(15) NULL DEFAULT CURRENT_TIMESTAMP,
  `activo` TINYINT NULL DEFAULT 1,
  `creado_en` DATETIME NULL,
  `elimininado_en` DATETIME NULL,
  `sexo` CHAR(1) NULL,
  `tipo_documento` VARCHAR(30) NULL,
  `nro_documento` VARCHAR(40) NULL,
  `ts_usuario_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ts_cliente_ts_usuario1_idx` (`ts_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_ts_cliente_ts_usuario1`
    FOREIGN KEY (`ts_usuario_id`)
    REFERENCES `db_tiendita-saludable`.`ts_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_tiendita-saludable`.`ts_metodo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tiendita-saludable`.`ts_metodo_pago` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `img` VARCHAR(255) NULL DEFAULT CURRENT_TIMESTAMP,
  `detalle_importante` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_tiendita-saludable`.`ts_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tiendita-saludable`.`ts_venta` (
  `id` INT NOT NULL,
  `` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `ts_metodo_pago_id` INT NOT NULL,
  `ts_cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ts_venta_ts_metodo_pago_idx` (`ts_metodo_pago_id` ASC) VISIBLE,
  INDEX `fk_ts_venta_ts_cliente1_idx` (`ts_cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_ts_venta_ts_metodo_pago`
    FOREIGN KEY (`ts_metodo_pago_id`)
    REFERENCES `db_tiendita-saludable`.`ts_metodo_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ts_venta_ts_cliente1`
    FOREIGN KEY (`ts_cliente_id`)
    REFERENCES `db_tiendita-saludable`.`ts_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_tiendita-saludable`.`ts_seccion_web`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tiendita-saludable`.`ts_seccion_web` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(125) NULL,
  `titulo` VARCHAR(125) NULL,
  `color` VARCHAR(45) NULL,
  `tipo_seccion` VARCHAR(45) NULL,
  `estilo` VARCHAR(255) NULL,
  `orden` INT NULL,
  `limite_producto` VARCHAR(45) NULL,
  `activo` TINYINT NULL DEFAULT 1,
  `creado_en` DATETIME NULL DEFAULT on update CURRENT_TIMESTAMP,
  `modificado_en` DATETIME NULL DEFAULT on update CURRENT_TIMESTAMP,
  `borrado_en` DATETIME NULL DEFAULT on update CURRENT_TIMESTAMP,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_tiendita-saludable`.`ts_detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tiendita-saludable`.`ts_detalle_venta` (
  `id` INT NOT NULL,
  `catidad` VARCHAR(255) NULL,
  `precio_unitario` VARCHAR(255) NULL,
  `sub_total` DATETIME NULL DEFAULT on update CURRENT_TIMESTAMP,
  `ts_producto_id` INT NOT NULL,
  `ts_venta_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ts_producto_id`),
  INDEX `fk_ts_detalle_venta_ts_producto1_idx` (`ts_producto_id` ASC) VISIBLE,
  INDEX `fk_ts_detalle_venta_ts_venta1_idx` (`ts_venta_id` ASC) VISIBLE,
  CONSTRAINT `fk_ts_detalle_venta_ts_producto1`
    FOREIGN KEY (`ts_producto_id`)
    REFERENCES `db_tiendita-saludable`.`ts_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ts_detalle_venta_ts_venta1`
    FOREIGN KEY (`ts_venta_id`)
    REFERENCES `db_tiendita-saludable`.`ts_venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `db_tiendita-saludable`.`ts_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tiendita-saludable`.`ts_permiso` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `db_tiendita-saludable`.`ts_usuario_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tiendita-saludable`.`ts_usuario_permiso` (
  `ts_tipo_usuario_id` INT NOT NULL,
  `ts_permiso_id` INT NOT NULL,
  INDEX `fk_ts_usuario_permiso_ts_tipo_usuario1_idx` (`ts_tipo_usuario_id` ASC) VISIBLE,
  INDEX `fk_ts_usuario_permiso_ts_permiso1_idx` (`ts_permiso_id` ASC) VISIBLE,
  CONSTRAINT `fk_ts_usuario_permiso_ts_tipo_usuario1`
    FOREIGN KEY (`ts_tipo_usuario_id`)
    REFERENCES `db_tiendita-saludable`.`ts_tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ts_usuario_permiso_ts_permiso1`
    FOREIGN KEY (`ts_permiso_id`)
    REFERENCES `db_tiendita-saludable`.`ts_permiso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
